import 'server-only';

export {
  paginateRediscoverCandidates,
  REDISCOVER_CANDIDATE_POOL_SIZE,
  rerankRediscoverCandidates,
} from './diversity';
export { buildRediscoverReasons } from './explanations';
export {
  buildListeningWindowBoundaries,
  buildRotationExplanation,
  calculateListeningFreshness,
  calculateRecordedMomentum,
  calculateRecordedShare,
  calculateRepeatIntensity,
  calculateRotationEvidenceLevel,
  calculateRotationFrequency7,
  calculateRotationFrequency30,
  calculateRotationIntelligence,
  calculateRotationRecency,
  calculateTopTrackConcentration,
  classifyListeningWindow,
  collectListeningWindowSignals,
  collectRotationSignals,
} from './listening';
export { collectRediscoverSignals, MILLISECONDS_PER_DAY } from './signals';
export {
  calculateAffinityPressure,
  calculateAgeRelevance,
  calculateEvidenceLevel,
  calculateLibraryAgeDepth,
  calculateRecordedFrequencyPressure,
  calculateRecordedRecencyPressure,
  calculateRediscoverIntelligence,
  calculateVaultDepth,
} from './scoring';
export {
  BOUNDED_SOUND_FEATURES,
  buildSoundDistanceReasons,
  calculateSoundDistance,
  calculateSoundDistribution,
  calculateSoundProfileCoverage,
  rankClosestToSoundCenter,
  rankSonicOutliers,
  SOUND_EXPLANATION_FEATURE_ORDER,
} from './sound';
export type {
  AffinityRange,
  AffinitySignal,
  BoundedSoundFeature,
  CompleteBoundedSoundValues,
  DiversityCandidate,
  EvidenceLevel,
  IntelligenceReason,
  ListeningComparisonWindow,
  ListeningFreshnessState,
  ListeningWindowBoundaries,
  ListeningWindowSignals,
  RecordedMomentum,
  RecordedMomentumInput,
  RecordedMomentumItem,
  RediscoverComponentKey,
  RediscoverIntelligence,
  RediscoverSignals,
  RotationComponentKey,
  RotationExplanation,
  RotationIntelligence,
  RotationScoreComponent,
  RotationSignals,
  ScoreComponent,
  SoundCenter,
  SoundCoverageQuality,
  SoundDistanceCandidate,
  SoundDistanceReason,
  SoundDistribution,
  SoundProfileAvailability,
  SoundProfileCoverage,
  VaultDepthComponent,
  VaultDepthComponentKey,
} from './types';
